### ISSUE TITLE
Extract failure (on a semi-popular Morrowind mod from 2003)

### ISSUE THREAD

**Issue by Darklocq** [droe/acefile#5]
Error reported: 
  Airship/Sound/fx/tostran.wav failed to extract
  error extracting from solid archive, aborting

Not sure what a "solid" archive is.  Anyway, the offending file is the download here: http://mw.modhistory.com/download-68-110

Conditions: acefile downloaded from GitHub yesterday, used under MacOS X 10.12.4, with Python 3.5.2 as installed by MacPorts.

**Comment by droe** [comment]
Confirmed, latest acefile fails to extract `airship.ace` (MD5 `ee62ca66b0d5d152affcbc66bd3d6e28`), CRC error on `Airship/Sound/fx/tostran.wav`. unace 2.5 tests/extracts the archive successfully.

A solid archive is an ACE archive where the different files share the same decompression state, meaning that after a failed file in a solid archive, all subsequent files will fail to extract too. In a non-solid archive, decompression restarts from zero for each file, meaning that errors in a file don't affect subsequent files.

**Comment by droe** [comment]
b4c76eb08d3e059d5ed7b0b8a21034633ebe7b66 fixes the issue for `airship.ace` and all other SOUND mode samples available to me. Thank you for reporting the issue!

**Comment by Darklocq** [comment]
Schweet. It has worked on ever .ACE I've tried so far now, in the current version.
